[project]
name = "fastapi-start"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.5",
    "argon2-cffi>=25.1.0",
    "asgiref>=3.12.1",
    "asyncpg>=0.30.0",
    "black>=26.5.1",
    "celery-types>=0.26.0",
    "celery[redis]>=5.3.1",
    "fastapi-mail>=1.6.5",
    "fastapi[standard]>=0.140.13",
    "flower>=2.0.1",
    "itsdangerous>=2.2.0",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "redis>=8.1.0",
    "sqlmodel>=0.0.39",
]

[tool.fastapi]
entrypoint = "src.main:app"
