"""add Relationship attr and backpopulates to Book and User model

Revision ID: 4160eb862df8
Revises: cb5b82937ece
Create Date: 2026-08-07 10:42:46.148601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4160eb862df8'
down_revision: Union[str, Sequence[str], None] = 'cb5b82937ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
