"""add role to users, add author_id fkey to books

Revision ID: cb5b82937ece
Revises: 75ebfa4c1b20
Create Date: 2026-08-06 11:57:49.117894

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = "cb5b82937ece"
down_revision: Union[str, Sequence[str], None] = "75ebfa4c1b20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


user_role_enum = ENUM("USER", "ADMIN", name="userrole", create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum.create(op.get_bind(), checkfirst=True)  # custom addition by me

    op.create_foreign_key(None, "books", "users", ["author_id"], ["id"])
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("USER", "ADMIN", name="userrole"),
            server_default="USER",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
